### ISSUE TITLE
The "MU car" has wrong rail gauge.

### ISSUE THREAD

**Issue by ZGCosmo** [OpenTTD-JPplus/JPplusMU#156]
**Describe the bug:**
Please describe the bug/issue. 

1. What is the bug/issue?
The "MU car" for Narrow gauge is located in Standard gauge depot, I cannot use it for narrow gauge train

2. How did you make the bug/issue happen? 
Nothing, Just put the GRF and run.

3. What would fix the bug? 
Check the guage of MU cars and put them in the right gauges.

**Screenshots:**
![image](https://github.com/user-attachments/assets/181578ba-337b-44d5-8690-968c68dfc735)

**OpenTTD version:**
OTTD jgrpp 0.60.2

**Comment by ZGCosmo** [comment]
Add : This may caused when use track grf : "Japan Set3: Tracks".
When use JR+ Tracks, It goes right

**Comment by Tintinfan** [comment]
Hello @ZGCosmo an update has been published that should solve this.
